CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR NOT NULL,
    text VARCHAR NOT NULL,
    viewedTimes INTEGER NOT NULL DEFAULT 0,
    published BOOLEAN NOT NULL DEFAULT 0
);
